///                                                           ///
/// ModDota AbilityLuaSpellLibrary spells for Meepo           ///
///                                                           ///
/// Last Update: 7.07c                                        ///
///                                                           ///

"DOTAAbilities"
{
    //=================================================================================================================
    // Meepo: Earthbind
    //=================================================================================================================
    "worker_deposit_payload"
    {
        // General
        //-------------------------------------------------------------------------------------------------------------
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/worker/worker_deposit_payload.lua"
        "AbilityTextureName"            "acolyte"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
        "AbilityUnitTargetTeam"         "DOTA_UNIT_TARGET_TEAM_FRIENDLY"
        "AbilityUnitTargetType"         "DOTA_UNIT_TARGET_BASIC"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_YES"
        "SpellDispellableType"          "SPELL_DISPELLABLE_YES"
        "FightRecapLevel"               "1"


        // Casting
        //-------------------------------------------------------------------------------------------------------------
        "AbilityCastPoint"              "0.6"
        "AbilityCastRange"              "100"

        // Time
        //-------------------------------------------------------------------------------------------------------------
        "AbilityCooldown"               "0"

        // Cost
        //-------------------------------------------------------------------------------------------------------------
        "AbilityManaCost"               "0"

        // Special
        //-------------------------------------------------------------------------------------------------------------
        "AbilitySpecial"
        {
            "01"
            {
                "var_type"              "FIELD_INTEGER"
                "train_duration"              "10"
            }

        }
        "AbilityCastAnimation"      "ACT_DOTA_ATTACK"
    }
}
